/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module App {
    /** Generated from Sam.DbContext.EntityObjectId **/
    export interface IEntityObjectId {
        Id: string;
    }
    /** Generated from Sam.DbContext.TypeScriptUser **/
    export interface IUser {
        Id?: string;
        UserName?: string;
        PasswordHash?: string;
        Email?: string;
    }
}
