/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module App {
    /** Generated from Sam.DbContext.UserRole **/
    const enum UserRole {
        User = 0,
        Admin = 1,
    }
    /** Generated from Sam.DbContext.EntityObjectId<TKey> **/
    export interface IEntityObjectBaseId {
        Id: any;
        CreatedDate: string;
        CreatedById: string;
        JsonCreatedBy: App.IUser;
        ModifiedDate: string;
        ModifiedById: string;
        JsonModifiedBy: App.IUser;
    }
    /** Generated from Sam.DbContext.EntityObjectId **/
    export interface IEntityObjectId extends App.IEntityObjectBaseId {
    }
    /** Generated from Sam.DbContext.JsonUser **/
    export interface IUser {
        Id: string;
        UserName?: string;
        Email?: string;
        UserRole: App.UserRole;
        PasswordHash?: string;
    }
}
